### ISSUE TITLE
Hugin is erroneously interpreting GeoPandas dataframes as raster files

### ISSUE THREAD

**Issue by mneagul** [sage-group/hugin#21]
@alexm98 identified the following issue with Hugin:

```
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/hugin-env/bin/hugin", line 11, in <module>
    sys.exit(main())
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/hugin/tools/cli.py", line 59, in main
    args.func(args)
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/hugin/tools/train.py", line 38, in train_handler
    trainer.train_scenes(dataset_loader, validation_scenes=validation_loader)
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/hugin/engine/scene.py", line 82, in train_scenes
    log.info("Training data has %d tiles", len(train_data))
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/hugin/io/loader.py", line 481, in __len__
    self._num_tiles += len(tile_generator)
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/hugin/io/loader.py", line 130, in __len__
    area = backing_store.height * backing_store.width
  File "/home/alex/anaconda3/envs/hugin-env/lib/python3.7/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'height'
```

**Comment by alexm98** [comment]
As this issue cannot be replicated I will close this for now.
